### ISSUE TITLE
Does this plugin only log one transaction and lose the data on the next one?

### ISSUE THREAD

**Issue by adam-je** [UseMuffin/Footprint#12]
Seems to me that this plugin works similar to the Blame plugin. But I think we need to grow out these plugins to do more than just record a single user action on a record to having its own DB table that can LOG EVERY USER ACTION, thereby creating an opportunity for much deeper insight into user behavior and a records timeline/change log.

**Comment by ADmad** [comment]
What you are looking for is probably [AuditStash](https://github.com/lorenzo/audit-stash).

**Comment by adam-je** [comment]
Dude you're **awesome**!
