### ISSUE TITLE
Using Footprint beforeFind Event

### ISSUE THREAD

**Issue by justinatack** [UseMuffin/Footprint#17]
Hi,

Thanks for a great plugin, it works well for me.

I was wondering is it possible to use the beforeFind event to restrict the returned data by the Auth user_id?

I'm building a multi-tenant app and it would be great if Footprint could not only manage the save data but also restrict the find data.

I tried the following

UsersTable
```
        $this->addBehavior('Muffin/Footprint.Footprint', [
            'events' => [
                'Model.beforeSave' => [
                    'group_id' => 'new',
                    'created_by' => 'new',
                    'modified_by' => 'always'
                ],
                'Model.beforeFind' => [
                    'group_id'
                ]
            ],
            'propertiesMap' => [
                'group_id' => '_footprint.group_id',
            ],
        ]);
```

but I get 

```
Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'group_id' in where clause is ambiguous
```

This error could be easily fixed with Users.group_id but when I add that to the Footprint behaviour I get the following.

```
Cannot convert value to integer
```

Is it possible to use the Footprint plugin this way or it it only for saving data and not retrieving?

**Comment by jadb** [comment]
I believe it should work and unsure if this PR #11 resolves it. It's missing tests but try merging it locally and run your code again.

**Comment by justinatack** [comment]
Any chance this will be merged soon?

**Comment by jadb** [comment]
@justinatack can you confirm it resolved it for you?

**Comment by jadb** [comment]
Closing as PR seems to have resolved this. Please open a new issue if not.
