### ISSUE TITLE
$options['_footprint'] is multi entities when using JwtAuth plugin

### ISSUE THREAD

**Issue by ayman-alkom** [UseMuffin/Footprint#24]
In the case we are more than one authentication method (in my case : `Form` and `ADmad/JwtAuth.Jwt` ).

then noticed that the $options['_footprint']['id'] is not accessible from and I have to use 
$options['_footprint'][0]['id']
<pre class='xdebug-var-dump' dir='ltr'>
<b>object</b>(<i>Cake\ORM\Entity</i>)[<i>228</i>]
  <i>protected</i> '_properties' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=2)</i>
      0 <font color='#888a85'>=></font> 
        <b>array</b> <i>(size=14)</i>
          'id' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'e666e197-74d3-4d6c-9ae1-2be9eab76349'</font> <i>(length=36)</i>
          'full_name' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'aaa'</font> <i>(length=5)</i>
          'username' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'aaa'</font> <i>(length=10)</i>
          'email' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'aaa@gmail.com'</font> <i>(length=20)</i>
          'email_token' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          'email_verified' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
          'email_token_expires' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          'active' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
          'password_token' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          'password_token_expires' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          'role' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'ADMIN'</font> <i>(length=5)</i>
          'last_login' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          'created' <font color='#888a85'>=></font> 
            <b>object</b>(<i>Cake\I18n\Time</i>)[<i>216</i>]
              ...
          'modified' <font color='#888a85'>=></font> 
            <b>object</b>(<i>Cake\I18n\Time</i>)[<i>219</i>]
              ...
      1 <font color='#888a85'>=></font> 
        <b>object</b>(<i>ADmad\JwtAuth\Auth\JwtAuthenticate</i>)[<i>140</i>]
          <i>protected</i> '_token' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlNjY2ZTE5Ny03NGQzLTRkNmMtOWFlMS0yYmU5ZWFiNzYzNDkiLCJleHAiOjE0NjM0ODY4NTl9.3OOTe8UHrLIjR-VzG8w8EI3CKoU1fMHXxC-nuwh5mi0'</font> <i>(length=165)</i>
          <i>protected</i> '_payload' <font color='#888a85'>=></font> 
            <b>object</b>(<i>stdClass</i>)[<i>139</i>]
              ...
          <i>protected</i> '_error' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          <i>protected</i> '_defaultConfig' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=6)</i>
              ...
          <i>protected</i> '_registry' <font color='#888a85'>=></font> 
            <b>object</b>(<i>Cake\Controller\ComponentRegistry</i>)[<i>103</i>]
              ...
          <i>protected</i> '_passwordHasher' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          <i>protected</i> '_needsPasswordRehash' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>false</font>
          <i>protected</i> '_config' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=13)</i>
              ...
          <i>protected</i> '_configInitialized' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
  <i>protected</i> '_original' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_hidden' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_virtual' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_className' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
  <i>protected</i> '_dirty' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=2)</i>
      0 <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
      1 <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
  <i>protected</i> '_new' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
  <i>protected</i> '_errors' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_invalid' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=0)</i>
      <i><font color='#888a85'>empty</font></i>
  <i>protected</i> '_accessible' <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=2)</i>
      '*' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
      'id' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
  <i>protected</i> '_registryAlias' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'Users'</font> <i>(length=5)</i>
</pre>

**Comment by ADmad** [comment]
How exactly would one reproduce this issue?

Also using a stateful (Form) and stateless (JwtAuth.Jwt) authenticator provider is not advisable. You should configure AuthComponent to use only one based on some criteria, for e.g. use Jwt only for urls with prefix "api".

**Comment by bravo-kernel** [comment]
@ADmad two authentication providers is actually exactly what the jwt-blog describes. `FormAuthenticate` to handle the initial json body (form) post of username, password. I seem to remember there was no alternative solution.

**Comment by ADmad** [comment]
@bravo-kernel Yes your tutorial does use `FormAuthenticate` to allow users to generate token by authenticating with their username / password but it does not add the user info to the session, which is the right thing to do.

**Comment by bravo-kernel** [comment]
@ADmad I see, missed your stateful/stateless explanation there. Thanks for confirming.

**Comment by ayman-alkom** [comment]
> How exactly would one reproduce this issue?
In fact I just followed this [tutorial](http://www.bravo-kernel.com/2015/04/how-to-add-jwt-authentication-to-a-cakephp-3-rest-api/)

this is my initializing code:

```php
        $this->loadComponent('Auth', [
            'authorize' => [
                'Controller'
            ],
            'storage' => 'Memory',
            'authenticate' => [
                'Form' => [
                    'userModel' => 'MyApp.Users',
                    'fields' => [
                        'username' => 'email',
                        'password' => 'password'
                    ],
                    'scope' => [
                        'Users.email_verified' => 1
                    ]
                ],
                'ADmad/JwtAuth.Jwt' => [
                    'parameter' => 'token',
                    'userModel' => 'MyApp.Users',
                    'scope' => ['Users.active' => 1],
                    'fields' => [
                        'username' => 'id'
                    ],
                    'queryDatasource' => true
                ]
            ],
            'unauthorizedRedirect' => false,
            'checkAuthIn' => 'Controller.initialize'
        ]);
```

**Comment by ayman-alkom** [comment]
and this happens just with Api prefix

**Comment by ADmad** [comment]
Okay, I'll try to reproduce this.

**Comment by bravo-kernel** [comment]
You might try to compare to (and strip using) the end state sources for the blog. https://github.com/bravo-kernel/application-examples/blob/master/blog-how-to-add-jwt-authentication-to-a-cakephp-3-rest-api/src/Controller/Api/AppController.php

**Comment by ADmad** [comment]
Yup using your tutorial repo will same me some time.

**Comment by ayman-alkom** [comment]
@ADmad I test the case of using JWT witout Form and still the same

**Comment by ADmad** [comment]
The debug you have provided above is for which variable/property ?

**Comment by ayman-alkom** [comment]
I dumped it from [here](https://github.com/UseMuffin/Footprint/blob/master/src/Auth/FootprintAwareTrait.php#L80)

`var_dump($data)`

**Comment by ADmad** [comment]
Please check the dump of `$user` in [_getUserInstanceFromArray()](https://github.com/UseMuffin/Footprint/blob/master/src/Auth/FootprintAwareTrait.php#L145). Let see if something goes haywire when creating entity from user array or before that.

**Comment by ayman-alkom** [comment]
the result is :
<pre class='xdebug-var-dump' dir='ltr'>
<b>array</b> <i>(size=2)</i>
  0 <font color='#888a85'>=></font> 
    <b>array</b> <i>(size=14)</i>
      'id' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'e666e197-74d3-4d6c-9ae1-2be9eab76349'</font> <i>(length=36)</i>
      'full_name' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'Ayman'</font> <i>(length=5)</i>
      'username' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'aymanalkom'</font> <i>(length=10)</i>
      'email' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'aymanalkom@gmail.com'</font> <i>(length=20)</i>
      'email_token' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      'email_verified' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
      'email_token_expires' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      'active' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
      'password_token' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      'password_token_expires' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      'role' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'ADMIN'</font> <i>(length=5)</i>
      'last_login' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      'created' <font color='#888a85'>=></font> 
        <b>object</b>(<i>Cake\I18n\Time</i>)[<i>169</i>]
          <i>public</i> 'date' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'2016-04-04 11:11:18'</font> <i>(length=19)</i>
          <i>public</i> 'timezone_type' <font color='#888a85'>=></font> <small>int</small> <font color='#4e9a06'>3</font>
          <i>public</i> 'timezone' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'UTC'</font> <i>(length=3)</i>
      'modified' <font color='#888a85'>=></font> 
        <b>object</b>(<i>Cake\I18n\Time</i>)[<i>214</i>]
          <i>public</i> 'date' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'2016-04-06 13:39:52'</font> <i>(length=19)</i>
          <i>public</i> 'timezone_type' <font color='#888a85'>=></font> <small>int</small> <font color='#4e9a06'>3</font>
          <i>public</i> 'timezone' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'UTC'</font> <i>(length=3)</i>
  1 <font color='#888a85'>=></font> 
    <b>object</b>(<i>ADmad\JwtAuth\Auth\JwtAuthenticate</i>)[<i>137</i>]
      <i>protected</i> '_token' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlNjY2ZTE5Ny03NGQzLTRkNmMtOWFlMS0yYmU5ZWFiNzYzNDkiLCJleHAiOjE0NjM0ODY4NTl9.3OOTe8UHrLIjR-VzG8w8EI3CKoU1fMHXxC-nuwh5mi0'</font> <i>(length=165)</i>
      <i>protected</i> '_payload' <font color='#888a85'>=></font> 
        <b>object</b>(<i>stdClass</i>)[<i>139</i>]
          <i>public</i> 'sub' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'e666e197-74d3-4d6c-9ae1-2be9eab76349'</font> <i>(length=36)</i>
          <i>public</i> 'exp' <font color='#888a85'>=></font> <small>int</small> <font color='#4e9a06'>1463486859</font>
      <i>protected</i> '_error' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      <i>protected</i> '_defaultConfig' <font color='#888a85'>=></font> 
        <b>array</b> <i>(size=6)</i>
          'fields' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=2)</i>
              ...
          'userModel' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'Users'</font> <i>(length=5)</i>
          'scope' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=0)</i>
              ...
          'finder' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'all'</font> <i>(length=3)</i>
          'contain' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          'passwordHasher' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'Default'</font> <i>(length=7)</i>
      <i>protected</i> '_registry' <font color='#888a85'>=></font> 
        <b>object</b>(<i>Cake\Controller\ComponentRegistry</i>)[<i>103</i>]
          <i>protected</i> '_Controller' <font color='#888a85'>=></font> 
            <b>object</b>(<i>App\Controller\Api\ReportsController</i>)[<i>77</i>]
              ...
          <i>protected</i> '_loaded' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=3)</i>
              ...
          <i>protected</i> '_eventManager' <font color='#888a85'>=></font> 
            <b>object</b>(<i>Cake\Event\EventManager</i>)[<i>104</i>]
              ...
          <i>protected</i> '_eventClass' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'\Cake\Event\Event'</font> <i>(length=17)</i>
      <i>protected</i> '_passwordHasher' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      <i>protected</i> '_needsPasswordRehash' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>false</font>
      <i>protected</i> '_config' <font color='#888a85'>=></font> 
        <b>array</b> <i>(size=13)</i>
          'fields' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=2)</i>
              ...
          'userModel' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'MyApp.Users'</font> <i>(length=11)</i>
          'scope' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=1)</i>
              ...
          'finder' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'all'</font> <i>(length=3)</i>
          'contain' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
          'passwordHasher' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'Default'</font> <i>(length=7)</i>
          'header' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'authorization'</font> <i>(length=13)</i>
          'prefix' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'bearer'</font> <i>(length=6)</i>
          'parameter' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'token'</font> <i>(length=5)</i>
          'allowedAlgs' <font color='#888a85'>=></font> 
            <b>array</b> <i>(size=1)</i>
              ...
          'queryDatasource' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
          'unauthenticatedException' <font color='#888a85'>=></font> <small>string</small> <font color='#cc0000'>'\Cake\Network\Exception\UnauthorizedException'</font> <i>(length=45)</i>
          'key' <font color='#888a85'>=></font> <font color='#3465a4'>null</font>
      <i>protected</i> '_configInitialized' <font color='#888a85'>=></font> <small>boolean</small> <font color='#75507b'>true</font>
</pre>

**Comment by ADmad** [comment]
Okay so the array itself is incorrect, it should be just:

```
array (size=14)
      'id' => string 'e666e197-74d3-4d6c-9ae1-2be9eab76349' (length=36)
      'full_name' => string 'Ayman' (length=5)
      'username' => string 'aymanalkom' (length=10)
      'email' => string 'aymanalkom@gmail.com' (length=20)
      'email_token' => null
      'email_verified' => boolean true
      'email_token_expires' => null
      'active' => boolean true
      'password_token' => null
      'password_token_expires' => null
      'role' => string 'ADMIN' (length=5)
      'last_login' => null
      'created' => 
        object(Cake\I18n\Time)[169]
          public 'date' => string '2016-04-04 11:11:18' (length=19)
          public 'timezone_type' => int 3
          public 'timezone' => string 'UTC' (length=3)
      'modified' => 
        object(Cake\I18n\Time)[214]
          public 'date' => string '2016-04-06 13:39:52' (length=19)
          public 'timezone_type' => int 3
          public 'timezone' => string 'UTC' (length=3)
```

Keep backtracking and find out where it gets messed up :)

**Comment by ayman-alkom** [comment]
then the question is how [ `$event->data` ](https://github.com/UseMuffin/Footprint/blob/master/src/Auth/FootprintAwareTrait.php#L64) has been made

**Comment by ADmad** [comment]
I think we found the root cause of problem. [This](https://github.com/cakephp/cakephp/blob/9899909363e80ad4c160d1e136dfa754d4f05401/src/Controller/Component/AuthComponent.php#L700). So `$event->data[0]` would be the user record and `$event->data[1]` would be the provider.

So changing https://github.com/UseMuffin/Footprint/blob/master/src/Auth/FootprintAwareTrait.php#L64 to `$this->_listener->setUser($this->_getCurrentUser($event->data[0]));` should fix the issue.

**Comment by ayman-alkom** [comment]
I will try it, but as sometimes there is no `$event->data[0]`, that happens just when using JWT.
in the [quesk fix](https://github.com/UseMuffin/Footprint/pull/25/files#diff-3b9180247afea54418f8136f12a2f84aR84) I made I worked with the two cases

**Comment by ADmad** [comment]
> I will try it, but as sometimes there is no $event->data[0], that happens just when using JWT.

Can you please check the stack trace and find out in what case there is no there is no $event->data[0], cause for `Auth.afterIdentify` event it should always exist.

**Comment by ADmad** [comment]
If you can get online on slack/IRC we can get through this faster :)

**Comment by ayman-alkom** [comment]
you are right, it is exist always

**Comment by ayman-alkom** [comment]
@ADmad yes it has been fixed, thanks
