### ISSUE TITLE
Use footprint across plugins

### ISSUE THREAD

**Issue by kristiyandobrev** [UseMuffin/Footprint#30]
I have split my application into [plugins](http://book.cakephp.org/3.0/en/plugins.html) . 

Im trying to use `Footprint` and I have the following setup:

- I have  `FootprintAwareTrait` called inside  `src/Controller/AppController`
- I have my `Tables` and `Models` in `src` and `Controllers` and `Templates` in `plugins/Foo`. 

The above setup didn't work.

So I  left  `FootprintAwareTrait;` inside  `src/Controller/AppController` and tried to move some stuff around:

- Moved everything in `src` - **WORKED**  
- Moved everything in `plugins/MyPluginName` - **WORKED**  

But I still want to have `Tables` and `Models` in `src` and `Controllers` and `Templates` in `plugins/Foo`, so any ideas if it's possible to use the `Footprint `plugin in that case ? 

I have managed to reproduce that in a new project and made a [repo](https://github.com/kristiyandobrev/footprint-plugins-issue).

**Comment by ADmad** [comment]
Add `debug(get_class($this->Footprints));` to `index()` method of `TestPlugin/src/Controller/FootprintsController.php`.  What output do you get?

**Comment by kristiyandobrev** [comment]
I got this one as output:

`'Cake\ORM\Table'`

**Comment by ADmad** [comment]
So you see a `Table` instance is used (which doesn't have Footprint behavior attached) since you don't have a table class for that model in your plugin.

**Comment by kristiyandobrev** [comment]
Is that intended by design? Because that (models in src and the rest in a plugin) works for all other plugins including thr Blame one.

**Comment by jadb** [comment]
@kristiyandobrev, cake automatically creates a table for you when a class (file) couldn't be found for the table you want to instantiate. When doing so, it doesn't attach any plugin's behavior/listener by default.

**Comment by ADmad** [comment]
If you want you `Footprints` controller in plugin to use `Footprints` model from main app you will have to explicitly call `$this->loadModel('Footprints')` else by default it will always try to load `Footprints.Footprints` model from your plugin.

**Comment by kristiyandobrev** [comment]
Where should I call `$this->loadModel('Footprints')` @ADmad ?

**Comment by ADmad** [comment]
Do it in `beforeFilter()` instead of `initialize()`. Instead of explicit loading you can also try setting `$modelClass` property of controller to `Footprints`. If you need more assistance please use the cakephp form or IRC / Slack not this issues tracker.

**Comment by Spriz** [comment]
Why would the plugin require loading tables in the `beforeFilter()` rather than `initialize()` ? 😄
