### ISSUE TITLE
Inline assignment bug

### ISSUE THREAD

**Issue by dereuromark** [UseMuffin/Footprint#33]
```php
if ($user === null && (empty($this->Auth) || !$user = $this->Auth->user())) {
```
I am pretty sure the last one - the inline assignment  (dangerous!) - is not doing what it is supposed to do.
It will always evaluate to false because the missing braces before ! bool cast.
So better to avoid inline assignment completely.

**Comment by jadb** [comment]
Not sure what I follow 😞. 

If `Auth->user()` returns a user, it will not return `false`. It will also assign the logged in user to `$user` which was checked to be `null` on same line to re-use later down the code. If all attempts to get a user fail, then the condition is a pass.

It does work (has worked for everyone thus far). Do you have a failing test?

**Comment by dereuromark** [comment]
Well, I would probably just refactor it for clarity.
