### ISSUE TITLE
Using _footprint in Custom Rules Checker

### ISSUE THREAD

**Issue by temp1029** [UseMuffin/Footprint#35]
I am trying to use this plugin to pass logged in user details to a custom rule checker, however when I look at the $options array in the __invoke function, the key isn't present.

I am fairly certain the plugin has been installed and is operating correctly, as in the beforeSave function of my model (when I log the $options array to a file) I do see the _footprint key, just not when I log it from the __invoke function my custom rule checker.

I've been tying on my own to figure out why this hasn't worked. I've both read the different "Issues" already submitted here and tried to better understand how Traits and Events work in general (since these seem to be central to the functioning of this plugin).  I think it has something to do with when adding the _footprint key is triggered. Is there a different event this needs to be listening on?  I tried to figure this out, but I couldn't seem to wrap my head around it. 

Any help would be appreciated and I can provide whatever details or code might be helpful.  Thanks in advance.

**Comment by jadb** [comment]
What's your use case? I mean why are you checking rules using footprint? I have a feeling that it might not be the best approach and would rather point you in the right direction, or better understand how to help you achieve what you want using Footprint.

**Comment by temp1029** [comment]
I am building a self-managed system, where users need to be able to control things attached to their account but not things attached to other user's accounts.  This includes adding other users to the account.  I played with the idea of creating a behavior, since I need it to be used across multiple models, with a beforeSave function, to handle this but the rule checker seemed to be a more natural place.

Of course I could be completely wrong about putting this into the model at all and it might be better suited to go in the Controller, but I couldn't think of (or don't know about) a way to make this easily usable across multiple controllers and actions.

**Comment by jadb** [comment]
Isn't this authorization related? A [custom `Authorize` object](http://book.cakephp.org/3.0/en/controllers/components/authentication.html#creating-custom-authorize-objects) is what you need in this case, with total access to the user's session.
