### ISSUE TITLE
Integration tests fail with cake 3.3.4

### ISSUE THREAD

**Issue by Spriz** [UseMuffin/Footprint#36]
With Cake 3.3.3 the following is included in our `setUp()` - and that puts content in the `'_footprint'` key in the table's `$options` array - but `3.3.4` and `3.3.5` this array is `null` :-/

```
use Muffin\Footprint\Event\FootprintListener;

//

    public function setUp()
    {
        parent::setUp();

        // put the login logic here instead in each function
        // Set session data
        $this->session([
            'Auth' => [
                'User' => [ /**/ ],
                    'language' => [
                        'short_code' => 'en_US',
                        'currency_id' => '83e0e78d-115e-423f-82dc-cf3f9da37b3d',
                    ],
                ],
            ],
        ]);
        $this->listener = new FootprintListener();
    }
```

**Comment by Spriz** [comment]
Now it's in the correct place @jadb! 😂

**Comment by Spriz** [comment]
@ADmad this is the place where https://github.com/UseMuffin/Trash/issues/14 should've been created :P

**Comment by Spriz** [comment]
Anyone have any suggestions on this one?

**Comment by jadb** [comment]
Sorry. 

Am not sure how this code was working by looking at it. Particularly, how was `FootprintListener` getting the `User` entity without it being passed in the constructor or using `setUser()`?

I would suggest creating a `User` instance, passing it to the listener and passing its array form to the session. That's how I would set it up.

**Comment by Spriz** [comment]
@jadb it's an integration test case, so I assumed by setting the auth data Footprint would pick it up itself - and the reason for current code is because of #31.

**Comment by Spriz** [comment]
Oh, and I tried setting the data in the Listener's contructor, and w/ the setUser method, but it's still not picking it up @jadb

**Comment by Spriz** [comment]
@ADmad / @jadb are there anything obvious I seem to be missing here? The issue is still not fixed on our end - do you guys have an example on a test case and how you'd set it up?

**Comment by DanielPenkov** [comment]
Hi, I have the same problem. I have a test for the `add` method, Im  setting the auth data in the test, but `_footprint` key  is missing from the table's $options. It is very strange that if I make a get request like `$this->get('/');` in the test, before the actual post `_footprint' key` appears in  $options. Any suggestions what could be the reason for this?

Gist: https://gist.github.com/DanielPenkov/7300cd98d25683d4673ef410b7dd715d

**Comment by ADmad** [comment]
It would be much easier to get to the bottom of this if someone could make a PR for this repo itself with integration test showing the problem.

**Comment by swiffer** [comment]
I'm facing the same problem. Isn't the gist containing everything needed? If it really helps I can add a the test to this repo?

@DanielPenkov / @Spriz any workarounds/solutions from your side?
