### ISSUE TITLE
Support Model.beforeRules

### ISSUE THREAD

**Issue by ypnos** [UseMuffin/Footprint#40]
Right now rules cannot make use of the information provided by the FootprintBehavior, as it is injected after the rules checking step.

However rules might need to check on it.
Usage example:

> Records can be locked for editing by a user. The rule ensures that the modifying user is the one holding the lock, if there is any (by comparing modifiedby in the entity with lockedby in the database).

I don't know the design decision to use beforeSave, but I would assume beforeRules is the better place in general. As the rules check the consistency of the entity and the user data might play part in it.

I volunteer to do a PR that enables Model.beforeRules next to Model.beforeSave.

**Comment by Spriz** [comment]
This would clearly be a good usecase, surprised we didn't need this yet.

**Comment by ypnos-web** [comment]
To be fair, I assume most developers do custom checks in the controller.

**Comment by ADmad** [comment]
PR welcome. Current `beforeSave()` could be turned into a generic `handler()` method and `implementedEvents()` method can be added to the behavior which returns event list based on those configured in `config['events']`.

**Comment by Spriz** [comment]
Aye, but the thinner controllers the btter @ypnos-web ! :D

**Comment by ypnos-web** [comment]
I finally had a closer look at this. From the event list of `Cake\ORM\Table` I don't see any other events than `beforeFind()`, `beforeRules()` and `beforeSave()` where FootprintBehavior would be really useful. As `beforeFind()` is a special case anyway, maybe we just use a common method called by both `beforeRules()` and `beforeSave()`? (In my early test I just added a `beforeRules()` that delegates to `beforeSave()`.)

I also wonder how this should be tested, do we write a new test class? `FootprintBehaviorTest` is pretty much hard-wired into testing the `beforeSave` event.

Any feedback would be welcome before I spend more time on the PR.

**Comment by ADmad** [comment]
Done in #45
