### ISSUE TITLE
loadModel method, a belongsToMany relation and Footprint plugin doesn't work

### ISSUE THREAD

**Issue by xavier83ar** [UseMuffin/Footprint#42]
I've found a very very particular (and somehow rare) bug, it took me some time to figure out what's the problem or at least how to reproduce it.

In short, if this 4 things happens together, you get a fatal error:

- `FootprintAwareTrait` is used 
- User model has a belongsToMany relation
- Make use of `loadModel` method to load User model inside `Controller::initialize`
- Find Users containing things from the belongsToMany relation

If all that occurs, then you'll get:

```
Fatal error: Uncaught Error: Call to a member function getName() on null in 
.../src/ORM/Association/BelongsToMany.php on line 1371
```

While this is cakephp 3.4, I've tested with cakephp 3.3.x and the bug is also present.

I've made a cakephp test app with the minimun code needed to recreate this error, [https://github.com/xavier83ar/cakephp-testapp](https://github.com/xavier83ar/cakephp-testapp)

Cloning the repo, `composer install`, `bin/cake migrations migrate`, `bin/cake server` should be enough to get it up and running.

Go to `/testing/not-working` to see the bug, and go to `/testing/working` and `/testing/working-too` to see two other ways of achieve the same result that do work.

Also I've noticed that if Users model gets removed from `TableRegistry` right after it's used in `\Muffin\Footprint\Auth\FootprintAwareTrait::_circumventEventManager` (line 131) everything works fine; adding this line:

```php
TableRegistry::remove($this->_userModel);
```

I don't have enough free time to go deeper and find out what's the real issue and where it cames from. Also it could be a plugin bug or a CakePHP bug, I can't be sure, but as I faced it when using the plugin, I decided to post here. I think that's all.

**Comment by ADmad** [comment]
> Make use of loadModel method to load User model inside Controller::initialize

Why do you need to load a model so early?  Can't you move it to `beforeFilter()`?

**Comment by xavier83ar** [comment]
> Why do you need to load a model so early? Can't you move it to beforeFilter()?

Honestly, I don't know, I guess because I saw examples of loadComponent there so I put loadModel there too. I realize now that I rarely use beforeFilter since cakephp 3.x

Moving it to beforeFilter avoids the issue, I think I may move it as there is no real reason why it's in initialize after all.

But, is it wrong to load models on Controller::initialize? Is there a recomended way of loading models (beforeFilter vs initialize)? I ask you this because if there is, I didn't know that.

**Comment by juniorionut** [comment]
@xavier83ar i had to find "the hard" way also that loading models in "Controller::initialize" OR even in "Component::initialize" causes this issue.

**Comment by ADmad** [comment]
Warning has been added to readme against loading models in Controller::initialize().

**Comment by juniorionut** [comment]
Thanks!
