### ISSUE TITLE
Does not work with Cake 3.5.*

### ISSUE THREAD

**Issue by piotrpoz** [UseMuffin/Footprint#47]
Hi guys,

Any success using this behaviour with Cake 3.5? I've tried to with 3.4 as well but no luck. It uses deprecated methods but even when these are fixed to new ones it does not move along.

When printing out in beforeSave the entity I get that user_id record is dirty but set to empty value.

**Comment by ypnos-web** [comment]
I tested the behavior with CakePHP 3.5.1.
It seems you need to be more specific to find the problem.

**Comment by Oxicode** [comment]
`
"Argument 1 passed to Muffin\Footprint\Event\FootprintListener::__construct() must be an instance of Cake\ORM\Entity, string given, called in /home/ubuntu/workspace/vendor/muffin/footprint/src/Auth/FootprintAwareTrait.php on line 57 and defined ◀"
`
![image](https://user-images.githubusercontent.com/1320709/30384599-61346578-986a-11e7-9b5b-d4c2a08d0a55.png)

**Comment by ADmad** [comment]
Unless someone can provide specific details on how to reproduce the problem there's nothing I can do. I don't have the time to do a Q&A to figure out your problem. The plugin works fine for 3.5.

**Comment by Oxicode** [comment]
Hola,
el problema es intermitente, yo tampoco sé con seguridad baje que condiciones pasa ese error, solo que cuando cuando vuelvo a refrescar la pagina (F5) funciona correctamente.

**Comment by saviobosco** [comment]
@Oxicode have u resoved the issue ? I had such problem but later resolved it . Mine was caused by trying to load a misspelled element in a layout like this 
`$this->element('misspelledElement')` 
Still don't know why it triggered that particular Exception instead of MissingElementException.
