### ISSUE TITLE
Error on non existent element

### ISSUE THREAD

**Issue by matthewwoollard** [UseMuffin/Footprint#48]
`<?= $this->Element('does_not_exist') ?>`
Results in:

Argument 1 passed to Muffin\Footprint\Event\FootprintListener::__construct() must be an instance of Cake\ORM\Entity or null, string given, called in /home/vagrant/Apps/vtta.local/vendor/muffin/footprint/src/Auth/FootprintAwareTrait.php on line 57

**Comment by ADmad** [comment]
Well then don't try to use non existent element :slightly_smiling_face:. I don't see how it ends up getting a string argument. If you can track down the details a provide a fix a pull request is welcome.
