### ISSUE TITLE
Changing the _footprint option key

### ISSUE THREAD

**Issue by elboletaire** [UseMuffin/Footprint#58]
Is there an easy way to set the option key (set by default to `_footprint`)?

By easy I mean without the need to rewrite a method (which is what I'm currently doing):

~~~php
<?php
    use FootprintAwareTrait {
        footprint as realFootprint;
    }

    public function footprint(Event $event)
    {
        self::realFootprint($event);

        $this->_listener->setConfig('optionKey', '_customFootprintKey');
    }
~~~

**Comment by ADmad** [comment]
What you have shown is enough for a rarely required feature :slightly_smiling_face:.

**Comment by elboletaire** [comment]
Ok!
