### ISSUE TITLE
Upgrade to cake 4.0.0

### ISSUE THREAD

**Issue by octisfall** [UseMuffin/Footprint#65]
Hi, do you plan to upgrade plugin?

**Comment by ADmad** [comment]
It is on my to-do list but a pull request to upgrade would be more than welcome.

One thing to consider is the plugin currently relies on core's AuthComponent which is deprecated, so the Cake 4 compatible version should support the new Authentication plugin too.

**Comment by ADmad** [comment]
https://github.com/UseMuffin/Footprint/releases/tag/2.0.0-beta
