### ISSUE TITLE
FootprintListener->handleEvent is never called

### ISSUE THREAD

**Issue by androideo** [UseMuffin/Footprint#79]
## Expected Behavior

- created_by is set with user_id
- FootprintAwareTrait->footprint sets the listener for handleEvent
- EventManager->dispatch() for event=`beforeFilter` finds FootprintListener
- FootprintListener->handleEvent is called with the beforeFilter event, so that the user credentials in options will be set
- FootprintBehavior->dispatch is called with the beforeSave event, to set created_by 

## Actual Behavior
- created_by is empty
- FootprintAwareTrait->footprint sets the listener for handleEvent, even User Information is loaded correctly
- EventManager->dispatch() for event=`beforeFilter` DOES NOT find FootprintListener (but beforeSave Events)
- FootprintListener->handleEvent is NEVER called
- FootprintBehavior->dispatch IS ALWAYS called with the beforeSave event, but no user information found

## Steps to Reproduce the Problem
I am using the deprecated `AuthComponent` with `UsersModel` und I want to fill `created_by`.
So far there is no Association btw. `created_by` and `Users`.

Actually, I am unsure about what you mean by this: 
"FootprintBehavior attached to a model do not load the model inside Controller::initialize()"

I am using the Behavior in the `ArticlesTable` and access in the `ArticlesController` the by model `$this->Articles->get()` and `$this->Articles->patchEntity()` and `$this->Articles->save()`. Is that okay like this?

Anything that I might have missed?

## Specifications

  - CakePHP: 4.2.7
  - muffin/footprint: 2.0.3

**Comment by ADmad** [comment]
Following the order of the events calls can be quite tricky with such issues. That's why I have changed up the internals to no longer require using the `FootprintAwareTrait`.

Would you like to try the `dev` branch and see how it goes? https://github.com/UseMuffin/Footprint/tree/develop

**Comment by androideo** [comment]
Thanks for the idea, but after installing it from VCS it's still not working.
