### ISSUE TITLE
Is the Authentication plugin required for this plugin to work?

### ISSUE THREAD

**Issue by TechFanDan** [UseMuffin/Footprint#82]
I believe the application that I'm maintaining is using the Auth component (?)

```
$this->loadComponent('Auth', [
    'authorize' => 'Controller'
]);
```

I think I've gone through all the steps to install the Footprint plugin, but it's still not populating created_by and modified_by. I was wondering if the Authentication plugin was required for it to work?

**Comment by ADmad** [comment]
v3 of the plugin requires the Authentication plugin. You can use v2 instead which support the deprecated AuthComponent of the core too https://github.com/UseMuffin/Footprint/blob/2.0.3/README.md

**Comment by TechFanDan** [comment]
> v3 of the plugin requires the Authentication plugin. You can use v2 instead which support the deprecated AuthComponent of the core too https://github.com/UseMuffin/Footprint/blob/2.0.3/README.md

v2 would work with CakePHP 4.3  (that I failed to mention previously) ?
