### ISSUE TITLE
(1.x) Add a configuration option for the Authentication event name to check

### ISSUE THREAD

**Issue by jrbakooba** [UseMuffin/Footprint#83]
Hi, I'm running Cake 3.x and cannot upgrade to 4 (yet) but I _am_ using the new-and-improved Authentication and Authorization plugins from Cake (ergo, _not_ the AuthComponent anymore). I'm also using Footprint 1.x. 

When I updated the Authz plugins, the post-identify event name changed from `Auth.afterIdentify` to `Authentication.afterIdentify` and now my footprinting code doesn't work anymore because it isn't setting the current user.

My suggestion/request is to make the event name configurable (at the app level, so I don't have to do it every time I load the behavior) so that Footprint listens for the correct identify event before setting the current user.

I can't use the Footprint Middleware because it's in the 2.x branch, which requires Cake 4.

If there is an alternative solution I am all ears. Thanks! 🏰

**Comment by ADmad** [comment]
1.x branch won't be getting any updates. You can just copy the `FootprintAwareTrait` trait and change the event name and use that in your controller.
